// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Appointment is the predicate function for appointment builders.
type Appointment func(*sql.Selector)

// Clinic is the predicate function for clinic builders.
type Clinic func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Veterinarian is the predicate function for veterinarian builders.
type Veterinarian func(*sql.Selector)
